apiVersion: v1
kind: Service
metadata:
  name: codefestx
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: codefestx
  type: LoadBalancer
  loadBalancerIP: 35.204.42.40
